# Linear Algebra

In [2]:
import numpy as np

In [3]:
x1 = np.array([4, 5, 6])

In [4]:
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


##### We will represent a vector as a column vector, having multiple rows

In [5]:
x = np.array([[4], [5], [6]])
print(x)
print("\n")
print(x.shape)
print("\n")
print(x[0][0])

[[4]
 [5]
 [6]]


(3, 1)


4


In [6]:
# To flatten the column vector
x = x.reshape((-1,))
print(x)

[4 5 6]


## Matrices and Tensors

Tensor is an array with more than 2 axes.

In [7]:
#Here X is a matrix
X = np.array([[4,5,7],[10,11,13], [56, 80, 90]])
print(X.shape)
print(X)
print(X[1][2])

(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
13


In [8]:
#Here t is a tensor

t = np.array([[[4,5,6],[10,11,13]],[[56,80,90],[9,8,10]]])
print(t.shape)
print(t)

(2, 2, 3)
[[[ 4  5  6]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]


### Transpose

In [9]:
print(X)
xt = np.transpose(X)
print("\n")
print(xt)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]


[[ 4 10 56]
 [ 5 11 80]
 [ 7 13 90]]


### Broadcasting
You can add a scalar to a vector, and numpy will add it to each element in the vector

Similarly you can add a avector to a matrix, and numpy will add the vector to each column of the matrix

In [10]:
l = [1,2,3,4]
l = np.array(l)
l = l+1
print(l)
l = l**2
print(l)    

[2 3 4 5]
[ 4  9 16 25]


In [11]:
l = [[1,2,3,4],[4,5,6,7]]
l = np.array(l)
l = l+1
print(l)
l = l**2
print(l)  

[[2 3 4 5]
 [5 6 7 8]]
[[ 4  9 16 25]
 [25 36 49 64]]


### Matrix Multiplication

In [12]:
x = np.array([[4,5,6],[10,11,13],[45,65,2]])
y = np.array([[42,51,16],[1,1,3],[5,15,21]])
print(x)
print("\n")
print(y)

[[ 4  5  6]
 [10 11 13]
 [45 65  2]]


[[42 51 16]
 [ 1  1  3]
 [ 5 15 21]]


In [13]:
prod = np.dot(x,y)
print(prod)

[[ 203  299  205]
 [ 496  716  466]
 [1965 2390  957]]


### Element wise multiplication: Hadamard product

Do not confuse this with matrix multiplication.

In [14]:
z = np.eye(3)
print(x)
print(z)

[[ 4  5  6]
 [10 11 13]
 [45 65  2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(x*z)

[[ 4.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0.  2.]]


In [16]:
z = z*2
z = z+1
print(z)

[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]


### Norm of a vector
Norm can be thought of as a proxy for size of a vector.
- L1 norm is the absolute sum of all the members of a vector.

In [17]:
x = np.array([-5,3,10])
lp2 = np.linalg.norm(x)
print(lp2)

11.575836902790225


In [18]:
lp1 = np.linalg.norm(x,ord = 1)
print(lp1)

18.0


In [19]:
lpinf = np.linalg.norm(x,ord = np.inf)
print(lpinf)

10.0
