In [2]:
!pip install numpy


In [1]:
import numpy as np

## Few important functions in numpy

In [2]:
# 1. How to create a numpy array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
print(type(a))   #to check the type of array

<class 'numpy.ndarray'>


In [4]:
a.shape #to check the dimentions of array

(5,)

In [5]:
# 2D array
b = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
b.shape

(2, 4)

In [7]:
print(b.shape)

(2, 4)


In [8]:
# Create zeros, ones and custom array

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
brr = np.ones((2,3))
print(brr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Array of some constants
crr = np.full((3,2),5)
print(crr)

print("\n")

# Identity matrix
d = np.eye(4)
print(d)

[[5 5]
 [5 5]
 [5 5]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# Transpose
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [12]:
# Dot product
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [13]:
# Random numbers
np.random.randint(60,100,20)

array([70, 77, 82, 99, 69, 72, 71, 86, 70, 95, 97, 63, 84, 68, 83, 68, 91,
       80, 99, 84])

In [14]:
np.random.randint(10,100,(10,10))  #2D array of random numbers

array([[10, 88, 72, 76, 78, 98, 29, 51, 19, 40],
       [49, 31, 69, 45, 53, 15, 13, 84, 14, 23],
       [30, 88, 16, 95, 85, 51, 67, 86, 37, 38],
       [52, 88, 45, 49, 80, 71, 95, 20, 13, 57],
       [66, 87, 45, 70, 59, 68, 82, 48, 11, 41],
       [61, 76, 94, 48, 32, 64, 56, 38, 20, 85],
       [61, 41, 12, 50, 66, 59, 26, 11, 14, 63],
       [85, 69, 49, 38, 48, 88, 70, 89, 11, 10],
       [40, 59, 99, 98, 21, 44, 35, 45, 97, 46],
       [69, 76, 28, 44, 39, 63, 76, 34, 56, 25]])

In [15]:
matrix = np.random.randint(10,100,(5,5))
print(matrix)

[[98 76 67 47 24]
 [30 56 67 63 14]
 [46 25 41 61 70]
 [52 57 67 62 89]
 [53 80 47 95 86]]


In [16]:
randommatrix = np.random.random((2,3))
print(randommatrix)

[[0.55875226 0.68040575 0.66431501]
 [0.12985555 0.40367282 0.08981642]]


In [17]:
# To find max in a matrix
np.max(matrix)

98

In [18]:
# To find min in a matrix
np.min(matrix)

14

In [19]:
# To find index where min element is there
a = np.array([0, 1, 4, 4, -4, 6])
np.argmin(a)

4

In [20]:
# to find unique elements in a
np.unique(a)

array([-4,  0,  1,  4,  6])

# Program to find out the number with the highest frequency

In [21]:
c = np.array([1,2,3,4,4,4,4,2,2,7,1,1,8,7,6])
freq = np.unique(c, return_counts=True)
print(freq)

(array([1, 2, 3, 4, 6, 7, 8]), array([3, 3, 1, 4, 1, 2, 1], dtype=int64))


In [22]:
idx = np.argmax(freq[1])
element = freq[0][idx]
print(element)

4


# Slicing arrays (1D, 2D, 3D........)

In [23]:
matrix

array([[98, 76, 67, 47, 24],
       [30, 56, 67, 63, 14],
       [46, 25, 41, 61, 70],
       [52, 57, 67, 62, 89],
       [53, 80, 47, 95, 86]])

In [24]:
matrix[1:4,2:4]

array([[67, 63],
       [41, 61],
       [67, 62]])

In [25]:
# To update elements
matrix[1:4,2:4] = 0
print(matrix)

[[98 76 67 47 24]
 [30 56  0  0 14]
 [46 25  0  0 70]
 [52 57  0  0 89]
 [53 80 47 95 86]]


In [26]:
# Set some rows and columns with any values
z = np.zeros((3,3))
print(z)
print("\n")
z[1,:] = 5
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


## Data Types

In [27]:
print(z.dtype)

float64


In [28]:
z = np.zeros((3,3), dtype = np.int64)
print(z)
print("\n")
z[1,:] = 5
print(z)
print("\n")
print(z.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[0 0 0]
 [5 5 5]
 [0 0 0]]


int64


## Mathematical operations

In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,2],[7,4]])
print(x+y)
print("\n")
print(np.add(x,y))
print("\n")
print(np.subtract(x,y))

[[ 6  4]
 [10  8]]


[[ 6  4]
 [10  8]]


[[-4  0]
 [-4  0]]


In [30]:
#multiplication
print(x*y)
print("\n")
print(np.multiply(x,y))
print("\n")
print(x/y)
print("\n")
print(np.divide(x,y))

[[ 5  4]
 [21 16]]


[[ 5  4]
 [21 16]]


[[0.2        1.        ]
 [0.42857143 1.        ]]


[[0.2        1.        ]
 [0.42857143 1.        ]]


In [58]:
# Multiplication o9f vectors - dot produc ==> scalar
a = np.array([1,2,3,4])
b = np.array([1,0,9,4])
print(a.dot(b))

44


In [59]:
print(sum(a))

10


In [60]:
print(np.sum(x))
print(np.sum(x,axis = 0)) # gives column wise sum
print(np.sum(x,axis = 1)) # gives row wise sum

10
[4 6]
[3 7]


## Stacking of arrays

In [61]:
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  0 81 16]


In [62]:
a =  np.stack((a,b),axis = 0)
print(a)

[[ 1  2  3  4]
 [ 1  0 81 16]]


### Reshape a numpy array

print(a)
a = a.reshape((4,2))
print("\n")
print(a)

In [65]:
a = a.reshape((8,))
print(a)

[ 1  2  3  4  1  0 81 16]


## Numpy Random module
 - rand: Random values in a given shape.
 - randn : Return a sample (or samples) from the "standard normal" distribution.
 - randint : Return random integers from low(inclusive) to high(exclusive).
 - random : Return random floats in the half-open interval [0.0,1.0).
 - choice : Generates a random sample from a given 1-D array.
 - Shuffle : Shuffles the contents of a sequence.

In [66]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [75]:
# use seed to store the state of the random number so that next time you run a jupyter again it replicates the result as the
# numbers generated by this method are pseudo random numbers
np.random.seed(1)
np.random.shuffle(a)
print(a)

[14 43  4]


In [76]:
# returns values from standard normal distribution
a = np.random.rand(2,3)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [77]:
a = np.random.randint(2,50,3)
print(a)

[47  8 27]


In [78]:
# randomly pick one element from a array
ele = np.random.choice([1,3,2,6,5,7])
print(ele)

2


## Some more numpy functions

In [87]:
a = np.array([[1,2,3,4],[6,5,4,7]])
print(a)
print(np.min(a))
print("\n")
# Specify axis for the direction
print(np.min(a, axis=0))
print(np.min(a, axis=1))

[[1 2 3 4]
 [6 5 4 7]]
1


[1 2 3 4]
[1 4]


### Mean 
 average of all elements

In [88]:
b = np.array([1,2,3,4,5])
print(np.mean(b))
print("\n")
print(np.mean(a))
print("\n")
print(np.mean(a,axis = 0))

3.0


4.0


[3.5 3.5 3.5 5.5]


### Median

In [89]:
print(np.median(b))

3.0


### Average

In [90]:
print(b)
print(np.mean(b))

w = np.array([1,2,3,4,5])
print(np.average(b,weights=w))

[1 2 3 4 5]
3.0
3.6666666666666665


## Standard deviation and varience

In [95]:
u = np.mean(b)
myStd = np.sqrt(np.mean(abs(b-u)**2))
print(myStd)

1.4142135623730951


In [97]:
#Inbuilt function for standard deviation
dev = np.std(b)
print(dev)

1.4142135623730951


In [101]:
#Varience
print(myStd**2)
print(np.var(b))

2.0000000000000004
2.0
