In [2]:
!pip install numpy


In [3]:
import numpy as np

## Few important functions in numpy

In [6]:
# 1. How to create a numpy array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [7]:
print(type(a))   #to check the type of array

<class 'numpy.ndarray'>


In [8]:
a.shape #to check the dimentions of array

(5,)

In [9]:
# 2D array
b = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
print(b.shape)

(2, 4)


In [12]:
# Transpose
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [13]:
# Dot product
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

In [14]:
# Random numbers
np.random.randint(60,100,20)

array([77, 79, 71, 84, 67, 99, 67, 70, 89, 70, 87, 90, 80, 61, 75, 78, 63,
       60, 71, 78])

In [15]:
np.random.randint(10,100,(10,10))  #2D array of random numbers

array([[53, 82, 24, 12, 19, 37, 80, 55, 11, 90],
       [69, 16, 75, 26, 24, 18, 82, 71, 34, 34],
       [50, 19, 69, 83, 46, 18, 63, 78, 10, 40],
       [80, 72, 94, 92, 83, 99, 99, 23, 74, 91],
       [92, 97, 83, 80, 29, 87, 87, 31, 58, 41],
       [30, 35, 35, 25, 88, 63, 90, 28, 89, 92],
       [96, 81, 71, 77, 35, 27, 87, 66, 14, 88],
       [43, 65, 21, 14, 81, 42, 51, 58, 72, 51],
       [75, 52, 28, 54, 86, 28, 76, 10, 51, 65],
       [12, 72, 46, 27, 96, 69, 79, 11, 19, 11]])

In [16]:
matrix = np.random.randint(10,100,(5,5))
print(matrix)

[[83 32 34 87 52]
 [24 97 89 26 93]
 [42 25 75 63 39]
 [98 64 60 28 49]
 [34 75 70 74 20]]


In [19]:
# To find max in a matrix
np.max(matrix)

98

In [20]:
# To find min in a matrix
np.min(matrix)

20

In [21]:
# To find index where min element is there
a = np.array([0, 1, 4, 4, -4, 6])
np.argmin(a)

3

In [22]:
# to find unique elements in a
np.unique(a)

array([-4,  0,  1,  4,  6])

# Program to find out the number with the highest frequency

In [28]:
c = np.array([1,2,3,4,4,4,4,2,2,7,1,1,8,7,6])
freq = np.unique(c, return_counts=True)
print(freq)

(array([1, 2, 3, 4, 6, 7, 8]), array([3, 3, 1, 4, 1, 2, 1], dtype=int64))


In [29]:
idx = np.argmax(freq[1])
element = freq[0][idx]
print(element)

4


# Slicing arrays (1D, 2D, 3D........)

In [30]:
matrix

array([[83, 32, 34, 87, 52],
       [24, 97, 89, 26, 93],
       [42, 25, 75, 63, 39],
       [98, 64, 60, 28, 49],
       [34, 75, 70, 74, 20]])

In [32]:
matrix[1:4,2:4]

array([[89, 26],
       [75, 63],
       [60, 28]])